services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      CORS_ORIGINS: http://localhost:3000
      DATABASE_URL: postgresql://aitema:aitema@postgres:5432/ris
      REDIS_URL: redis://redis:6379/0
      SQL_ECHO: 'false'
      VAPID_PUBLIC_KEY: BAvePkzdLzfX776fjj_lG8x99nxufPHr_cyGVfMauoRiVpSyX14TJ9wqBlHaXJbK1srKtR4GPwyy3CXf_KHCwiU
      VAPID_PRIVATE_KEY: MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg-62SB29KELXHpHEqPhq4ZIyzE6ZPSJNwqqEKfigh0EahRANCAAQL3j5M3S831---n44_5RvMffZ8bnzx6_3MhlXzGrqEYlaUsl9eEyfcKgZR2lyWytbKyrUeBj8Mstwl3_yhwsIl
      VAPID_CLAIMS_EMAIL: admin@aitema.de
  elasticsearch:
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
    image: elasticsearch:8.11.0
    ports:
    - 9200:9200
    volumes:
    - esdata:/usr/share/elasticsearch/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXT_PUBLIC_OPARL_URL: http://localhost:8000/oparl/v1
  postgres:
    environment:
      POSTGRES_DB: ris
      POSTGRES_PASSWORD: aitema
      POSTGRES_USER: aitema
    healthcheck:
      interval: 5s
      retries: 5
      test:
      - CMD-SHELL
      - pg_isready -U aitema
      timeout: 5s
    image: postgres:16-alpine
    volumes:
    - pgdata:/var/lib/postgresql/data
  redis:
    healthcheck:
      interval: 5s
      retries: 5
      test:
      - CMD
      - redis-cli
      - ping
      timeout: 5s
    image: redis:7-alpine
    ports:
    - 6379:6379
version: '3.8'
volumes:
  esdata: null
  pgdata: null
